language: perl

os:
  - linux
  # - osx

# services:
  # - docker

perl:
  # - "5.26-extras"
  - "5.24-extras"
  - "5.22-extras"
  - "5.20-extras"
  - "5.18-extras"

install:
  - cpanm --skip-satisfied -n -q Gedcom Genealogy::Gedcom::Date Date::Parse Getopt::Std Geo::Coder::OSM Geo::Coder::XYZ Term::ANSIColor Lingua::EN::NameParse Lingua::EN::NameCase Lingua::EN::Numbers::Ordinate Tie::Static DateTime::Format::Natural B::Lint LWP::UserAgent::Throttled LWP::Simple URI URI::Find::Schemeless Sort::Key::DateTime Text::Names Text::Names::GB autodie IPC::System::Simple Memoize Lingua::EN::ABC warnings::unused Data::Fetch Lingua::EN::Inflect WWW::Scrape::FindaGrave Geo::Coder::List Text::Names::GB Geo::Coder::CA Geo::StreetAddress::US Locale::US Geo::Coder::Postcodes

script:
  - perl -MO=Lint ./gedcom
  - perl -c -Mwarnings::unused ./gedcom
