language: perl

os:
  - linux
  # - osx

# services:
  # - docker

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

install:
  - cpanm --skip-satisfied -n -q Gedcom Genealogy::Gedcom::Date Date::Parse Getopt::Std Geo::Coder::OSM Term::ANSIColor Lingua::EN::NameParse Lingua::EN::NameCase Lingua::EN::Numbers::Ordinate Tie::Static DateTime::Format::Natural B::Lint LWP::Simple URI URI::Find::Schemeless Sort::Key::DateTime Text::Names autodie IPC::System::Simple Memoize Lingua::EN::ABC warnings::unused

script:
  - perl -MO=Lint ./gedcal
  - perl -c -Mwarnings::unused ./ged2site
