os:
  - linux
  - osx
services:
  - docker
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - cpanm --installdeps --quiet --notest Gedcom Genealogy::Gedcom::Date Date::Parse Getopt::Std
  - cpanm --notest --quiet Gedcom Genealogy::Gedcom::Date Date::Parse Getopt::Std
script:
  - perl -c ./gedcal
